### ISSUE TITLE
Secret created from Cypher didn't sync with new change

### ISSUE THREAD

**Issue by lelecacat** [gomorpheus/morpheus-vault-plugin#2]
Hello, currently I've been trying the vault plugin. I think I've found an issue:
When I make a new vault secret from Tools → Cypher, and then change the secret value from vault UI (or cmd). The secret in the Cypher doesnt sync with the last change or new secret version for kv2.

Thank you

**Comment by cpdtaylor** [comment]
I am looking into this, thanks!

**Comment by cpdtaylor** [comment]
re-opening for now, as fix relies on a bump to Cypher Core
